### ISSUE TITLE
Cannot login or register

### ISSUE THREAD

**Issue by oscar666666** [herasymj/Health-Esteem#26]
It redirects me back to homepage after i hit submit button. Error page isn't displaying too.
Tried 
1. delete database
2. Add-Migration Initial
3. Update-Database
but still not working. ^{}^

**Comment by QuinnBast** [comment]
Hey Oscar,
In order to get the database working you need to delete the database in visual studios and just run "Update-Database" in the NuGet Command window. Once you've done that it should work. There is no need to run "Add-Migration Initial." 

Running "Add-Migration Initial" means that you are trying to add or alter the database with a table named 'Initial' Which I'm not sure if you're intending to do. Try running the above commands without "Add-Migration Initial'. If that doesn't work then that means when you ran "Add-Migration Initial" it altered the migration file and now tries to run the 'Initial' migration every time. In order to get around this you're likely going to have to revert the migrations file back to the version that is at the latest commit on the branch. I just deleted the database and performed these commands on my PC and it is working. Here's some screenshots:

![image](https://user-images.githubusercontent.com/22599103/49134277-aa46e300-f2a8-11e8-85da-a90d5ab65b1f.png)

![image](https://user-images.githubusercontent.com/22599103/49134394-feea5e00-f2a8-11e8-8141-ad921c40f116.png)

![image](https://user-images.githubusercontent.com/22599103/49134423-1590b500-f2a9-11e8-92d3-a3891af38fc3.png)

After doing this I was able to successfully register an account and login:

![image](https://user-images.githubusercontent.com/22599103/49134650-e3cc1e00-f2a9-11e8-84ed-4202c12fb1b9.png)

If problems still occur make sure you've stashed all your changes and are on a fresh copy of the branch with "git stash" and "git reset --hard HEAD", ensure you "git pull" as well.
